kind: pipeline
type: kubernetes
name: default

node_selector:
  physical-node: dev2

trigger:
  branch:
    - main
  event:
    - push
    - tag

workspace:
  path: /drone/src

steps:
  - name: build multiarch from dev
    image: docker.io/owncloudci/drone-docker-buildx:4
    privileged: true
    settings:
      cache-from: [ "registry.dev.format.hu/framework-scheduler" ]
      registry: registry.dev.format.hu
      repo: registry.dev.format.hu/framework-scheduler
      tags: latest
      dockerfile: Dockerfile
      username:
        from_secret: dev-hu-registry-username
      password: 
        from_secret: dev-hu-registry-password
      platforms:
        - linux/amd64
        - linux/arm64
    when:  
      event:
        - push

  - name: pull image to dockerhub
    image: docker.io/owncloudci/drone-docker-buildx:4
    privileged: true
    settings:
      cache-from: [ "safebox/framework-scheduler" ]
      repo: safebox/framework-scheduler
      tags: latest
      username:
        from_secret: dockerhub-username
      password: 
        from_secret: dockerhub-password
      platforms:
        - linux/amd64
        - linux/arm64
    when:  
      event:
        - tag